name: CI - Flask App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docker_workflow  # todos los comandos se ejecutan aquí

    steps:
      - name: 1.- Clonar repositorio
        uses: actions/checkout@v4

      - name: 2.- Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 3.- Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4.- Arrancar app Flask y probar endpoint
        run: |
          nohup python app.py &           # arranca en background
          sleep 5                         # espera a que arranque
          curl -f http://localhost:8080/hello

      - name: 5.- Ejecutar pruebas unitarias
        run: pytest -v || echo "No hay tests unitarios aún"

      - name: 6.- Construir imagen Docker
        run: docker build -t flask-app:latest .

      - name: 7.- Test de contenedor
        run: |
          docker run -d -p 8080:8080 flask-app:latest
          sleep 5
          curl -f http://localhost:8080/hello
