name: CI - Flask App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Entrar a docker_workflow
        run: cd docker_workflow

      - name: ðŸ“¦ Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r docker_workflow/requirements.txt
          pip install pytest

      - name: Ejecutar pruebas
        run: pytest docker_workflow/ -v

      - name: Construir imagen Docker
        run: docker build -t flask-app:latest .

      - name: Probar ejecuciÃ³n del contenedor
        run: |
          docker run -d -p 8080:8080 flask-app:latest
          sleep 5
          curl -f http://localhost:8080/hello
